apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-dev
  template:
    metadata:
      labels:
        app: react-app-dev
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: react-app
          image: uditdataxis12345/testing-proj-cicd:20260624071242-7e8df276 # {"$imagepolicy": "flux-system:react-app"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
