apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: react-app
          image: uditdataxis12345/testing-proj-cicd:20260618063958-950bfe15 # {"$imagepolicy": "flux-system:react-app"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
