apiVersion: apps/v1
kind: Deployment

metadata:
  name: react-app-prod

spec:
  replicas: 3

  selector:
    matchLabels:
      app: react-app-prod

  template:
    metadata:
      labels:
        app: react-app-prod

    spec:
      imagePullSecrets:
        - name: dockerhub-credentials

      containers:
        - name: react-app
          image: uditdataxis12345/testing-proj-cicd:20260618063958-950bfe15
          imagePullPolicy: Always

          ports:
            - containerPort: 80